version: '3.1'

services:
  db-soltys:
    image: mysql:8.0
    container_name: db-soltys
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress-soltys:
    depends_on:
      - db-soltys
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress-soltys
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db-soltys:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver-soltys:
    depends_on:
      - wordpress-soltys
    image: nginx:1.15.12-alpine
    container_name: webserver-soltys
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge